[project]
name = "movielens-venv"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "jupyter>=1.1.1",
    "pandas>=2.3.2",
    "seaborn>=0.13.2",
]
